### ISSUE TITLE
Scanned in products not stored. 

### ISSUE THREAD

**Issue by Connorabruce** [ivoxavier/kaltracker#11]
When scanning in foods using barcodes, those foods are not saved and cannot be re-added again, without once again scanning in the food. This is a problem for something like multipacks, where you may not have the full multipack with you when adding the food to the app. 

Would it be possible for food added by barcode to be stored the same way as food added manually?

Great app by the way.

**Comment by ivoxavier** [comment]
Hi Connorabruce, thank you for your _feedback_. Yes is something that I will improve in future releases.
